---
title: "Get started with the igoR package"
author: Diego Hernangómez
description: Introduction to the capabilities of the package.
bibliography: REFERENCES.bib
link-citations: true
vignette: >
  %\VignetteIndexEntry{Get started with the igoR package}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
fig-width: 6
fig-height: 4
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
    warning: false
    message: false
    out.width: "100%"
    out.height: "60%"
---

This vignette is meant to provide **useRs** with a visual, explorable
introduction to the capabilities of the **igoR** package.

The analysis is based on those provided in @pevehouse2020. For more information
on the IGO data sets and additional downloads, see [Intergovernmental
Organizations (v3)](https://correlatesofwar.org/data-sets/IGOs/).

*Note that the dyadic dataset is not provided in the package, due to its size
(\~500 MB in Stata `.dta` format). However,* `igo_dyadic()` *function provides
similar results.*

## Definitions

From @pevehouse2019:

> ### What is an IGO?
>
> The definition of an Intergovernmental Organization (IGO) on the original
> dataset is based on the following criteria:
>
> 1.  An IGO must consist of at least three members of the [COW-defined state
>     system](https://correlatesofwar.org/data-sets/cow-country-codes/).
> 2.  An IGO must hold regular plenary sessions at least once every ten years
> 3.  An IGO must possess a permanent secretariat and corresponding
>     headquarters.
>
> ### When does an IGO actually begin?
>
> The data sets begins to code an IGO by identifying the first year in which the
> organization functions. In some cases, individual members are listed by year
> of accession or signature.
>
> ### When does an IGO die?
>
> Version 3.0 of the IGO data set uses the following criteria:
>
> -   An organization is considered terminated when the following words were
>     used to describe the context of the organization:
>     -   Replaced;
>     -   Succeeded;
>     -   Superseded;
>     -   Integrated;
>     -   Merged;
>     -   Dies.

## Analysis

This section provides some quick analysis based on the figures of
@pevehouse2020.

### Initial Setup

```{r}
#| label: setup
library(igoR)

# Additional libraries
library(ggplot2)
library(dplyr)
```
