---
title: "List of IGOs and Countries"
bibliography: refs_igo.bib
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{List of IGOs and Countries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r knitropts, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 6, 
  fig.height = 4,
  out.width = "100%",
  out.height = "60%"
)

if (isFALSE(requireNamespace("reactable", quietly = TRUE))) {
  install.packages("reactable")
}

```


Annex with the list of IGOs (@doi:10.1177/0022343319881175) and 
countries @cow_2015 included on this package.


## List of IGOs

```{r igo, echo=FALSE}

library(igoR)
library(reactable)

igo <- igo_search()
reactable(igo,
          filterable = TRUE,
          searchable = TRUE,
          showPageSizeOptions = TRUE
          )

```



## List of Countries 

```{r countries, echo=FALSE}

cc <- cow_country_codes
reactable(cc,
          filterable = TRUE,
          searchable = TRUE,
          showPageSizeOptions = TRUE
          )

```

## Session Info

<details>
  <summary><strong>Details</strong></summary>
```{r session_info, echo=FALSE}
sessionInfo()

```
</details>

## References

