---
title: "List of IGOs and Countries"
description: >
  Interactive exploration of the data included on the package.
bibliography: REFERENCES.bib
link-citations: true
---

```{r knitropts, include=FALSE}
start_time <- Sys.time()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

Annex with the list of IGOs [@pevehouse2020] and countries
[@correlatesofwarproject2017] included on this package.

## List of IGOs

```{r igo, echo=FALSE}
library(igoR)
library(reactable)

igo <- igo_search()
reactable(igo[, 1:7],
  filterable = TRUE,
  defaultColDef = colDef(minWidth = 150, vAlign = "center"),
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  elementId = "igos"
)
```

## List of Countries

```{r countries, echo=FALSE}
cc <- states2016
reactable(cc,
  filterable = TRUE,
  searchable = TRUE,
  defaultColDef = colDef(minWidth = 150, vAlign = "center"),
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  elementId = "countries"
)
```

## Session info

<details>

<summary>Details</summary>

```{r session, echo=FALSE}
if (!require("sessioninfo")) {
  install.packages("sessioninfo")
}
sessioninfo::session_info()
```

</details>

## References
