---
title: "IGOs and states in the Correlates of War system"
description: >
  Interactive tables of the IGO and state system data included in igoR.
bibliography: REFERENCES.bib
link-citations: true
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
    warning: false
    message: false
---

This annex lists the IGOs [@pevehouse2020] and states in the Correlates of War
state system [@correlatesofwarproject2017] included with **igoR**.

## IGOs

```{r}
#| label: igo
#| echo: false
library(igoR)
library(reactable)

igo <- igo_search()
reactable(
  igo[, 1:7],
  filterable = TRUE,
  defaultColDef = colDef(minWidth = 150, vAlign = "center"),
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  elementId = "igos"
)
```

## States

```{r}
#| label: countries
#| echo: false
cc <- states2016
reactable(
  cc,
  filterable = TRUE,
  searchable = TRUE,
  defaultColDef = colDef(minWidth = 150, vAlign = "center"),
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  elementId = "countries"
)
```

## References
