---
title: "List of IGOs and Countries"
bibliography: refs_igo.bib
---

```{r knitropts, include=FALSE}

start_time <- Sys.time()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 6, 
  fig.height = 4,
  out.width = "100%",
  out.height = "60%"
)

if (isFALSE(requireNamespace("reactable", quietly = TRUE))) {
  install.packages("reactable")
}

```


Annex with the list of IGOs (@doi:10.1177/0022343319881175) and 
countries (@cow_2017) included on this package.


## List of IGOs

```{r igo, echo=FALSE}

library(igoR)
library(reactable)

igo <- igo_search()
reactable(igo[, 1:7],
          filterable = TRUE,
          searchable = TRUE,
          showPageSizeOptions = TRUE,
          striped = TRUE,
          paginationType = "jump"
          )

```



## List of Countries 

```{r countries, echo=FALSE}

cc <- states2016
reactable(cc,
          filterable = TRUE,
          searchable = TRUE,
          showPageSizeOptions = TRUE,
          striped = TRUE,
          paginationType = "jump"
          )

```

## Session Info

<details>
  <summary><strong>Details</strong></summary>
```{r session_info, echo=FALSE}
sessionInfo()

end_time <- Sys.time()
sessionInfo()

cat("***")

cat("vignette running time:")
end_time - start_time

```
</details>

## References

